# Jekyll configuration

name: K4KPK
description: My adventures in ham radio...
title: K4KPK

# url is currently only used only for the RSS feed in feed.xml AND for auto-redirects
#url: http://k4kpk.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
#baseurl: /jekyll-clean
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: false

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:title
paginate: 9
highlighter: rouge
markdown: kramdown
plugins: 
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-admin
exclude: ['README.md', 'LICENSE', 'vendor']
safe: true
whitelist: ['jekyll-redirect-from', 'jekyll-paginate']
port: 4001
encoding: utf-8

# Put all subdirecties here which are source to be generated into the site.
# If you don't, the symptom is that you'll be able to browse to the pages on GitHub, but not locally.
include: ['sota-guides']

# Not just _posts, but other folders too.  By default, tipue_search searches only *posts* and not other pages.
# Note: The variable in code is site.tipue_search.include.pages.
# "site" means "comes from _config.yml".  Dots get mapped to foo: bar: baz, in _config.yml.
tipue_search:
  include:
    pages: true
