name: K4KPK
description: My adventures in ham radio...
title: K4KPK
baseurl: ''
github: ''
gaaccount: ''
comments: false
isso: ''
disqus: ''
permalink: '/:title'
paginate: 9
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-admin
exclude:
  - README.md
  - LICENSE
  - vendor
safe: true
whitelist:
  - jekyll-redirect-from
  - jekyll-paginate
port: 4001
encoding: utf-8
include:
  - sota-guides
tipue_search:
  include:
    pages: true
defaults:
  - scope:
      type: posts
      path: ''
    values:
      layout: post
      tags: []
  - scope:
      path: ''
      type: pages
    values:
      layout: page
